# Array manipulation routines

In [2]:
import numpy as np

In [6]:
np.__version__

'2.3.2'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [7]:
x = np.ones((10, 10, 3))
x = x.reshape(2, 150)
print(x.shape)

(2, 150)


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.ravel(x, order="F")
print(x)

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.ravel(x)[4]
print(x)

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [ ]:
x = np.zeros((3, 4, 5))
y = x.transpose([1, 0, 2])
print(y.shape)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [ ]:
x = np.zeros((3,4))
y = x.transpose()
print(y.shape)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [ ]:
x = np.zeros((3, 4))
print (np.expand_dims(x, axis=1).shape)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [ ]:
x = np.zeros((3, 4, 1))
print(np.squeeze(x).shape)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [5]:
x = np.array([[1,2,3],
             [4,5,6]])
y = np.array([[7,8,9],
              [10,11,12]])
z = np.concatenate((x,y), axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [10]:
x = [1, 2, 3]
y = [4, 5 ,6]

z = list(zip(x, y))
print(z)


[(1, 4), (2, 5), (3, 6)]


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [12]:
x = [[1], [2], [3]]
y = [[4], [5] ,[6]]

z = list(zip(x, y))
print(z)


[([1], [4]), ([2], [5]), ([3], [6])]


Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [7]:
x = np.array([1,2,3,4,5,6,7,8,9])
a, b, c = np.split(x,[4,6])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6]
[7 8 9]


Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [11]:
x = np.array([[[0,1,2,3,],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])
a, b = np.split(x, [3], axis=2)

print(a)
print(b)


[[[ 0  1  2]
  [ 4  5  6]]

 [[ 8  9 10]
  [12 13 14]]]
[[[ 3]
  [ 7]]

 [[11]
  [15]]]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [12]:
x = np.array([[0,1,2,3,],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

a, b = np.split(x, 2, axis=1)

print(a)
print(b)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [13]:
x = np.array([[0,1,2,3,],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

a, b = np.split(x, 2, axis=0)

print(a)
print(b)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [12]:
x = np.array([0, 1, 2])
result = np.tile(x, (2, 2))
print(result)


[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [14]:
x = np.array([0,1,2])
result = np.repeat(x,2)
print(result)

[0 0 1 1 2 2]


Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [15]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
result = np.trim_zeros(x)
print(result)


[1 2 3 0 2 1]


Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [17]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])

unique_vals, counts = np.unique(x, return_counts=True)
print(unique_vals)
print(counts)


[1 2 3 4 5]
[2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [20]:
x = np.array([
    [1, 2],
    [3, 4]
])
a = np.flip(x, axis=1)
print(a)



[[2 1]
 [4 3]]


Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [21]:
x = np.array([[1, 2],
              [3, 4]])

result = np.flip(x, axis=0)
print(result)


[[3 4]
 [1 2]]


Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [22]:
x = np.array([[1, 2],
              [3, 4]])

result = np.rot90(x)
print(result)


[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [23]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

result = np.roll(x, 1, axis=1)
print(result)


[[4 1 2 3]
 [8 5 6 7]]
